version: '3.8'

services:
  app:
    build: .
    container_name: registration_api
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      API_TOKEN: ${API_TOKEN}
      PORT: ${PORT}
    ports:
      - "80:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: registration_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db-data:
